### ISSUE TITLE
Running duo_api_csharp

### ISSUE THREAD

**Issue by SaraRdn** [duosecurity/duo_api_csharp#1]

**Comment by davidluxford** [comment]
Create a C# project in Visual Studio, then add Duo.cs to that project, and
then make calls against the methods in that class.  For an example of
making a call, take a look at examples\DuoAdmin.cs.

BTW, I apologize for the delayed response!  We are normally much faster.
Please let us know if you have any other questions.

_David Luxford_
/ Senior Software Engineer

davidluxford@duosecurity.com

DuoSecurity.com https://duosecurity.com/

Better Security, Not Just More.
