### ISSUE TITLE
I have downloaded the code added the nugget package assembly but the project has no executable what am I doing wrong? 

### ISSUE THREAD

**Issue by sdougl** [duosecurity/duo_api_csharp#25]

**Comment by AaronAtDuo** [comment]
@sdougl Assuming you are talking about the actual client (in the duo_api_csharp folder), this is not intended to be an executable program.  It is just a library/SDK that you would use in a different program for making Duo API calls.

The code in the examples directory, however, is an executable program that demonstrates how to use the SDK.

**Comment by AaronAtDuo** [comment]
Closing out as inactive - please reopen if you have further questions.
